### ISSUE TITLE
Repeating TestIDs in traceability matrix

### ISSUE THREAD

**Issue by tkwilos** [metrumresearchgroup/mrgvalidate#81] opened 2022-08-09 13:58 UTC
When rendering the traceability matrix, there are multiple requirements with the same tests. That appears to be causing the tests to get listed multiple times for each requirement they're associated with, when they only need to be listed once.

<img width="176" alt="image" src="https://user-images.githubusercontent.com/67168516/183667861-292ec0b3-ff63-40d4-926b-00969e33271e.png">

**Comment by kyleam** [comment] 2022-08-09 15:04
@tkwilos Thanks for catching that.  It's surprising that nobody has spotted that until now, but I see it in the old docs too.

I don't know the details, but I know @barrettk and @seth127 are doing a large rework of a lot of this code.  I imagine the plan is to go with that for the next release, in which case we need to make sure the issue isn't in the rewrite.

However, in the meantime, I pushed a fix to the [mat-remove-dup-testids](https://github.com/metrumresearchgroup/mrgvalidate/compare/mat-remove-dup-testids) branch.  For your current set of docs, you could pull that in with 

```
> devtools::install_github("metrumresearchgroup/mrgvalidate", ref = "mat-remove-dup-testids") 
```

@seth127 @barrettk I'm not sure about the timeline of your changes.  Do you think the fix above is worth merging in until the rewrite lands?

**Comment by barrettk** [comment] 2022-08-09 19:13
@kyleam my opinion would be to not (though obviously whatever Seth says works for me lol). At this point we're basically releasing a brand new package with a similar entry point for generating the docs. Regardless, ill make sure that issue isnt in the new version

**Comment by kyleam** [comment] 2022-08-09 19:24
@barrettk 
>   Regardless, ill make sure that issue isnt in the new version.

Great, thanks.  Not sure what code/tests made it through to the rewrite, but of course feel free to port whatever you would like.\ from 0a158e4a8fc12edd4bbb04b0f2995cd724499828.

**Comment by barrettk** [comment] 2022-08-09 19:46
@kyleam Yeah the test suite is TBD. I talked about it with Seth a bit, and we may change how the tests work. We need to talk a bit more before I know if we're just going to "update" the tests to reflect the changes vs. starting from scratch. Ill make sure theres a test for that though. The one you made is short and sweet so ill likely grab the same code regardless of how the tests change

**Comment by seth127** [comment] 2022-08-09 19:55
That all sounds good. If @tkwilos is fine with building this portion of the docs off that dev branch as @kyleam suggested, then I think we can just let this sit for now and make sure @barrettk gets [this little fix](https://github.com/metrumresearchgroup/mrgvalidate/commit/0a158e4a8fc12edd4bbb04b0f2995cd724499828) into the refactor branch that he's working on.

**Closed** 2022-11-23 19:57 UTC
